version: '3.4'

services:
  mongodb:
    image: mongo
  
  redisinsights:
    image: redislabs/redisinsight:latest

  redisdb:
    image: redis:alpine

  analytics.api:
    image: ${DOCKER_REGISTRY-}analyticsapi
    build:
      context: .
      dockerfile: Services/Analytics/Analytics.API/Dockerfile
    depends_on:
      - mongodb

  webscraper.api:
    image: ${DOCKER_REGISTRY-}webscraperapi
    build:
      context: .
      dockerfile: Services/WebScraper/WebScraper.API/Dockerfile
    depends_on: 
      - redisdb

  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: Web/WebMVC/WebMVC/Dockerfile
    depends_on:
      - analytics.api
      - webscraper.api

volumes:
  mongo_data: 
  redisinsight_data:
