version: '3.4'

services:
  mongodb:
    image: mongo
  
  redisdb:
    image: redis:alpine

  analytics.api:
    image: ${DOCKER_REGISTRY-}analyticsapi
    build:
      context: .
      dockerfile: Services/Analytics/Analytics.API/Dockerfile
    depends_on:
      - mongodb

  webscraper.api:
    image: ${DOCKER_REGISTRY-}webscraperapi
    build:
      context: .
      dockerfile: Services/WebScraper/WebScraper.API/Dockerfile
    depends_on: 
      - redisdb


volumes:
  mongo_data: 