version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"

  redisinsights:
    container_name: redisinsights
    ports:
      - "8100:8001"
    volumes:
      - redisinsight_data:/data/redis

  analytics.api:
    container_name: analytics.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"

  webscraper.api:
    container_name: webscraper.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://mongodb:27017"
      - "DatabaseSettings__DatabaseName=StopwordDb"
      - "DatabaseSettings__CollectionName=Stopwords"
      - "CacheSettings__ConnectionString=redisdb:6379"
    ports:
      - "9001:80"

  webmvc: 
    container_name: webmvc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Apis__WebScraper=http://webscraper.api/"
    ports:
      - "8000:80"

